# Generated by Django 3.2.9 on 2021-12-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_stuff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_stuff',
        ),
    ]
