version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: poker4grig
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: db

